image: docker/compose
services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_DRIVER: overlay

before_script:
  - apk add --update py-pip &&
      pip install docker-compose

build:
  stage: build
  script:
    - docker-compose build
    - docker-compose up -d