image: docker:stable

stages:
  - build image
  - push to dockerhub

docker build:
  stage: build image
  script:
    - docker info
    - docker build -t scraper ./scraper

docker push:
  stage: push to dockerhub
  script:
    - echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin
    - docker push $REGISTRY_USER/scraper
