version: "3.3"

services:
  api:
    restart: always
    build: ./scraper
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_NAME: postgres
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      ALLOWED_HOST: '*'
      SECRET_KEY: key
  db:
    image: postgres
    restart: always
    container_name: db
    ports:
      - "5432:5432"