version: "3.3"
services:
  db:
    image: postgres
  web:
    build: .
    command:
      bash -c "python scraper/manage.py migrate --no-input && python scraper/manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/scraper
    ports:
      - "8080:8080"
    depends_on:
      - db