# Generated by Django 2.2 on 2019-07-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_content', models.TextField()),
                ('article_author', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['article_author'],
            },
        ),
    ]
